apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      upstream user_service {
        server user-service:80;
      }

      upstream chat_service {
        server chat-service:80;
      }

      server {
        listen 80;

        location /api/user/ {
          proxy_pass http://user_service/;
        }

        location /api/chat/ {
          proxy_pass http://chat_service/;
        }
      }
    }
