version: '3.7'

networks:
  bookie:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookie
      MYSQL_USER: bookie
      MYSQL_PASSWORD: bookie
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - bookie
    ports:
      - "3308:3306"

  user-service:
    image: nguyentanthanh0709/user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: bookie
      DB_PASSWORD: bookie
      DB_DATABASE: bookie
    depends_on:
      - mysql
    command: npm run dev
    ports:
      - "8180:8180"
    networks:
      - bookie

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: ChatDB
    volumes:
      - mongo-data:/data/db
    networks:
      - bookie
    ports:
      - "27018:27017"

  chat-service:
    image: nguyentanthanh0709/chat-service:latest
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    volumes:
      - ./chat-service:/app
    environment:
      NODE_ENV: development
      MONGO_DB_URI: mongodb://mongo:27017/ChatDB
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - "8181:8181"
    networks:
      - bookie
volumes:
  mysql:
  mongo-data: