apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: nguyentanthanh0709/chat-service:latest
          ports:
            - containerPort: 8181
          env:
            - name: NODE_ENV
              value: development
            - name: MONGO_DB_URI
              value: mongodb://mongo:27017/ChatDB
